
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Pushing GitHub Repo to Azure DevOps..
  displayName: 'PushToAzure'

- checkout: self

- script: |
    git remote add azure $(System.AccessToken)@$(Build.Repository.Uri)
    git push azure $(Build.SourceBranch)
  displayName: 'Push to Azure DevOps'
