
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- checkout: self

- script: |
    git remote add azure $(System.AccessToken)@$(Build.Repository.Uri)
    git push azure $(Build.SourceBranch)
  displayName: 'Push to Azure DevOps'
